### ISSUE TITLE
Update Capital City use case report

### ISSUE THREAD

**Issue by 40522829** [xx00a/Group6#101]
Capital City report needs to be aligned to the other reports for uniformity

**Comment by 40522829** [comment]
Updated the capital city use case report to reflect what other use case reports contains:
- added column names
- updated goal in context description
- corrected Extensions section as formatting was off and changed the first line as well

**Comment by 40522829** [comment]
Code merged to develop

**Comment by xx00a** [comment]
Updates made. Discussed with team.
