### ISSUE TITLE
Update CapitalCity Class and SQL Statements

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#113]
- Port over your SQL commands (from your xxxxReport.class) to ReportEngine.class
- Make sure reportSQL[X] corresponds with the report ID indicated on README.me (VERY important for testing)
- Your SQL variable (N) should be defined as XXXXX in the SQL text (so it is replaced by the method at runtime)

**Comment by 40522829** [comment]
- Capital City SQL statemetns added to ReportEnging.class
- Changed rID hashtable to reflect the assessment requirements

**Comment by 40522829** [comment]
Changes done over the week. Now pushed to develop
