### ISSUE TITLE
Update REPORT_CAPITAL_CITY References

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#117]
- See ReportEngine class
- Make sure your reports are correctly referencing the class you worked on
- Example: rID.put (6, REPORT_COUNTRY)

Constants are:

REPORT_CAPITAL_CITY
REPORT_CITY
REPORT_COUNTRY
REPORT_LANGUAGES
REPORT_POPULATION

**Comment by 40522829** [comment]
Changes done on feature/nginx_integration which was pushed to 130_nginx_java_update branch. The latter has now been merged into develop
