### ISSUE TITLE
Update Needed to HTML Output in ReportEngine

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#123]
Please see line 327 in ReportEngine, branch #122 

Each person needs to review the class of report (1-5) in the SWITCH statement.

1. Update table headers
2. Update row result (this needs to match the header of your SQL output exactly)

My case 3 (Country Report) is done. Please feel free to copy and reuse code to test your reports.

**Comment by 40522829** [comment]
Changes done on feature/nginx_integration to add the SQL statements for the Capital City report

**Comment by xx00a** [comment]
Feature implemented and done.
