### ISSUE TITLE
Report 32

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#157]
Needs to be reverted - only pulling one language, not multiple

**Comment by avison9** [comment]
I did the one language before but upon reading the the requirement again, it has to be the 5 languages on display.
"_The number of people who speak the following the following languages from greatest number to smallest, including the percentage of the world population: Chinese, English, Hindi, Spanish, Arabic_"
if its 1 language per query, then there wont be need for sorting from highest to lowest number.

**Comment by avison9** [comment]
Guess this can be closed then?

**Comment by xx00a** [comment]
Yes, merged with "pre-develop" for today's call. Thanks.
