### ISSUE TITLE
Questions for the professor for week 4

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#59]
- We want to clarify how/where user stories are introduced. What document?? Example is iffy in lab.
- I'll ask if we need other badges in our README.md for our project
- What does the professor mean by the following:
The population of people, people living in cities, and people not living in cities in each continent.
The population of people, people living in cities, and people not living in cities in each region.
The population of people, people living in cities, and people not living in cities in each country.

**Comment by 40522829** [comment]
- Q1 answer : in the use case report
- Q2 anser : use other badges for coverage from another place apart from shields.io
- Q3 answer : select sum(population) from country where CountryCode ="GBP";

Additional info: 
- we need to add Class diagrams into our Use Case reports
- Use an org like WHO. User will be an admin for example
- not uml folder but UseCases folder
- use other badges for coverage cause not in shields.io

**Comment by xx00a** [comment]
Discussed with team on call. No issues.
