### ISSUE TITLE
Create Capital City SQL for Report

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#63]
Create SQL statements for all requirements concerning capital cities
- All the capital cities in the world organised by largest population to smallest.
- All the capital cities in a continent organised by largest population to smallest.
- All the capital cities in a region organised by largest to smallest.
- The top N populated capital cities in the world where N is provided by the user.
- The top N populated capital cities in a continent where N is provided by the user.
- The top N populated capital cities in a region where N is provided by the user.

**Comment by 40522829** [comment]
Class has been created and pushed into the feature/capital_city_report branch

**Comment by 40522829** [comment]
Added the code below in capital_city.sql. You can find it under the sql folder under the Group6 repo:

-- All the capital cities in the world organised by largest population to smallest.
SELECT b.Name, a.Name, b.Population FROM country a INNER JOIN city b ON a.Capital = b.ID ORDER BY 3 DESC, 1;

-- All the capital cities in a continent organised by largest population to smallest.
SELECT b.Name, a.Name, a.Continent, b.Population FROM country a INNER JOIN city b ON a.Capital = b.ID ORDER BY 3, 4 DESC, 1;

-- All the capital cities in a region organised by largest to smallest.
SELECT b.Name, a.Name, a.Region, b.Population FROM country a INNER JOIN city b ON a.Capital = b.ID ORDER BY 3, 4 DESC, 1;

-- The top N populated capital cities in the world where N is provided by the user.
SELECT b.Name, a.Name, b.Population FROM country a INNER JOIN city b ON a.Capital = b.ID ORDER BY 3 DESC, 1 LIMIT 10;

-- The top N populated capital cities in a continent where N is provided by the user.
SELECT b.Name, a.Name, a.Continent, b.Population FROM country a LEFT JOIN city b ON a.Capital = b.ID WHERE a.Continent = "Asia" ORDER BY 4 DESC, 1 LIMIT 10;

-- The top N populated capital cities in a continent where N is provided by the user.
SELECT b.Name, a.Name, a.Region, b.Population FROM country a LEFT JOIN city b ON a.Capital = b.ID WHERE a.Region = "Melanesia" ORDER BY 4 DESC, 1 LIMIT 10;

**Comment by xx00a** [comment]
Discussed with team, complete, and closed out.
