### ISSUE TITLE
Create Population SQL for Report

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#64]
Create SQL statements for all requirements concerning populations
The population of people, people living in cities, and people not living in cities in each continent.
The population of people, people living in cities, and people not living in cities in each region.
The population of people, people living in cities, and people not living in cities in each country.

**Comment by fredy9669** [comment]
The population of people, people living in cities, and people not living in cities in each continent.
The population of people, people living in cities, and people not living in cities in each region.
The population of people, people living in cities, and people not living in cities in each country.

The name of the continent/region/country.
The total population of the continent/region/country.
The total population of the continent/region/country living in cities (including a %).
The total population of the continent/region/country not living in cities (including a %).

**Comment by fredy9669** [comment]
SELECT city.countrycode FROM city JOIN country ON city.countrycode = country.code  WHERE continent = "Asia" GROUP BY city.countrycode;

mysql> SELECT SUM(country.population), country.continent  FROM city JOIN country ON city.countrycode = country.code  GROUP BY country.continent;
+-------------------------+---------------+
| SUM(country.population) | continent     |
+-------------------------+---------------+
|             95330838000 | North America |
|            900937599400 | Asia          |
|             16179610000 | Africa        |
|             55118944000 | Europe        |
|             48533025000 | South America |
|               307500750 | Oceania       |
+-------------------------+---------------+


mysql> SELECT SUM(city.population), country.continent  FROM city JOIN country ON city.countrycode = country.code  GROUP BY country.continent;
+----------------------+---------------+
| SUM(city.population) | continent     |
+----------------------+---------------+
|            697604103 | Asia          |
|            241942813 | Europe        |
|            168250381 | North America |
|            135838579 | Africa        |
|             13886149 | Oceania       |
|            172037859 | South America |
+----------------------+---------------+

**Comment by fredy9669** [comment]
mysql> SELECT (SUM(city.population)+SUM(country.population)) AS TotalPopulation, (SUM(city.population)) AS CityPopulation, (SUM(country.population)) AS NotInCityPopulation , country.region
 FROM city JOIN country ON city.countrycode = country.code  GROUP BY country.region;

<img width="433" alt="image" src="https://user-images.githubusercontent.com/98422181/153754967-c1a46ea2-f7ec-45af-a3a4-84395fa03a10.png">

**Comment by fredy9669** [comment]
mysql> SELECT (SUM(city.population)+SUM(country.population)) AS TotalPopulation, (SUM(city.population)) AS CityPopulation, (SUM(country.population)) AS NotInCityPopulation , country.name  FROM city JOIN country ON city.countrycode = country.code  GROUP BY country.name ORDER BY TotalPopulation DESC;

<img width="491" alt="image" src="https://user-images.githubusercontent.com/98422181/153755190-948c4e07-f124-4891-8cca-94466b184a27.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/98422181/153755208-78093d0a-ae99-4289-aa06-6699d1afebcd.png">
<img width="491" alt="image" src="https://user-images.githubusercontent.com/98422181/153755225-1779f05b-0854-46b2-94a5-10dba191df34.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/98422181/153755247-5c0be46a-2a52-411e-bd83-fff78bdda802.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/98422181/153755263-2744b61d-5b6f-4712-8962-bd8f8931e017.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/98422181/153755287-a387506e-4a58-47c3-afa9-34f281998e93.png">

**Comment by fredy9669** [comment]
mysql> SELECT (SUM(city.population)+SUM(country.population)) AS TotalPopulation, (SUM(city.population)) AS CityPopulation, (SUM(country.population)) AS NotInCityPopulation , country.continent FROM city JOIN country ON city.countrycode = country.code GROUP BY country.continent ORDER BY TotalPopulation DESC;

**Comment by fredy9669** [comment]
ADDED:
The population of the world
The population of a continent
The population of a region

**Comment by fredy9669** [comment]
SELECT country.continent, 
	   (SUM(DISTINCT(country.population)) + SUM(city. population)) AS 'Total Population',
	   SUM(DISTINCT(country.population)) AS 'NOT in cities', 
	   (((SUM(DISTINCT(country.population))) / (SUM(DISTINCT(country.population)) + SUM(city.population)))*100) AS 'NOT in cities(%)',
	   SUM(city. population) AS 'IN cities',
	   (((SUM(DISTINCT(city.population))) / (SUM(DISTINCT(country.population)) + SUM(city.population)))*100) AS 'IN cities(%)'
	   FROM country JOIN city ON city.countrycode = country.code 
	   GROUP by country.continent;

<img width="704" alt="image" src="https://user-images.githubusercontent.com/98422181/154837651-bb54c8e0-0563-4c5f-b804-90eb1910f614.png">

**Comment by fredy9669** [comment]
SELECT country.region, 
	   (SUM(DISTINCT(country.population)) + SUM(city. population)) AS 'Total Population',
	   SUM(DISTINCT(country.population)) AS 'NOT in cities', 
	   (((SUM(DISTINCT(country.population))) / (SUM(DISTINCT(country.population)) + SUM(city.population)))*100) AS 'NOT in cities(%)',
	   SUM(city. population) AS 'IN cities',
	   (((SUM(DISTINCT(city.population))) / (SUM(DISTINCT(country.population)) + SUM(city.population)))*100) AS 'IN cities(%)'
	   FROM country JOIN city ON city.countrycode = country.code 
	   GROUP by country.region;

<img width="709" alt="image" src="https://user-images.githubusercontent.com/98422181/154838022-ec7922c6-e6ef-49c6-9570-c1d793de552d.png">

**Comment by fredy9669** [comment]
SELECT country.name, 
	   (SUM(DISTINCT(country.population)) + SUM(city. population)) AS 'Total Population',
	   SUM(DISTINCT(country.population)) AS 'NOT in cities', 
	   (((SUM(DISTINCT(country.population))) / (SUM(DISTINCT(country.population)) + SUM(city.population)))*100) AS 'NOT in cities(%)',
	   SUM(city. population) AS 'IN cities',
	   (((SUM(DISTINCT(city.population))) / (SUM(DISTINCT(country.population)) + SUM(city.population)))*100) AS 'IN cities(%)'
	   FROM country JOIN city ON city.countrycode = country.code 
	   GROUP by country.name;

<img width="700" alt="image" src="https://user-images.githubusercontent.com/98422181/154838334-2b06a1ad-71e9-430f-8bc5-4bc77a1d0c74.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/98422181/154838348-a276fe91-2d5c-4453-84f8-7a5ad5410265.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/98422181/154838359-264b78cb-03f8-4eff-bbf6-1f71206f29cd.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/98422181/154838369-2ca69749-32b9-4820-8a47-fc715ffe8e57.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/98422181/154838373-98a96e80-df15-49b5-9e77-7afb0993d61d.png">
<img width="673" alt="image" src="https://user-images.githubusercontent.com/98422181/154838390-28eb826e-3e15-4a08-a45a-a0b4722c5826.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/98422181/154838402-1f5d45bf-faa0-46fd-9071-ffd0fab63cbd.png">

**Comment by fredy9669** [comment]
SELECT (SUM(DISTINCT(country.population)) + SUM(city. population)) AS 'Total Population Of World'
	   FROM country JOIN city ON city.countrycode = country.code;

<img width="117" alt="image" src="https://user-images.githubusercontent.com/98422181/154838814-22b7ed90-b314-4fa0-8e07-ff95b9476a2d.png">

**Comment by fredy9669** [comment]
SELECT (SUM(DISTINCT(country.population)) + SUM(city. population)) AS 'Population of a continent'
FROM country JOIN city ON city.countrycode = country.code WHERE country.continent = '';

<img width="134" alt="image" src="https://user-images.githubusercontent.com/98422181/154839026-ee7fc456-23bb-4de5-880e-2c4767a3faad.png">

**Comment by fredy9669** [comment]
SELECT (SUM(DISTINCT(country.population)) + SUM(city. population)) AS 'Population of a region'
FROM country JOIN city ON city.countrycode = country.code WHERE country.region = '';

<img width="159" alt="image" src="https://user-images.githubusercontent.com/98422181/154839660-ccd1f193-deee-4c70-b0f5-54e2e1eeb6b0.png">

**Comment by fredy9669** [comment]
SQL Working and Java code pushed through.

**Comment by fredy9669** [comment]
NEW QUERIES!!! CORRECTED

SELECT country.continent,
(SUM(DISTINCT(country.population))) AS 'Total Population',
(SUM(DISTINCT(country.population)) - SUM(city.population)) AS 'NOT in cities',
((SUM(DISTINCT(country.population)) - SUM(city.population))) / (SUM(DISTINCT(country.population)))*100 AS 'NOT in cities(%)',
SUM(city. population) AS 'IN cities',
(((SUM(DISTINCT(city.population))) / (SUM(DISTINCT(country.population)))*100)) AS 'IN cities(%)'
FROM country JOIN city ON city.countrycode = country.code
GROUP by country.continent;


SELECT country.region,
(SUM(DISTINCT(country.population))) AS 'Total Population',
(SUM(DISTINCT(country.population)) - SUM(city.population)) AS 'NOT in cities',
((SUM(DISTINCT(country.population)) - SUM(city.population))) / (SUM(DISTINCT(country.population)))*100 AS 'NOT in cities(%)',
SUM(city. population) AS 'IN cities',
(((SUM(DISTINCT(city.population))) / (SUM(DISTINCT(country.population)))*100)) AS 'IN cities(%)'
FROM country JOIN city ON city.countrycode = country.code
GROUP by country.region;

SELECT country.name,
(SUM(DISTINCT(country.population))) AS 'Total Population',
(SUM(DISTINCT(country.population)) - SUM(city.population)) AS 'NOT in cities',
((SUM(DISTINCT(country.population)) - SUM(city.population))) / (SUM(DISTINCT(country.population)))*100 AS 'NOT in cities(%)',
SUM(city. population) AS 'IN cities',
(((SUM(DISTINCT(city.population))) / (SUM(DISTINCT(country.population)))*100)) AS 'IN cities(%)'
FROM country JOIN city ON city.countrycode = country.code
GROUP by country.name;


SELECT (SUM(DISTINCT(country.population))) AS 'Population of a continent'
FROM country JOIN city ON city.countrycode = country.code WHERE country.continent = '';

SELECT (SUM(DISTINCT(country.population))) AS 'Population of a region'
FROM country JOIN city ON city.countrycode = country.code WHERE country.region = '';

SELECT (SUM(DISTINCT(country.population))) AS 'Total Population Of World'
FROM country JOIN city ON city.countrycode = country.code;
