### ISSUE TITLE
Application Architecture Design

### ISSUE THREAD

**Issue by TomaszMuchaDev** [xx00a/Group6#72]

**Comment by xx00a** [comment]
Pseduo-code:

- Create New SQL connection (from a class)
- Create New HTML builder class
- Load new array of reports (ID 1..32, with corresponding columns to include, SQL command)

Loop (size of array) do
 - run query defined in array against SQL object
 - filter based on array parameters 
 - pass result of SQL results to HTML object so it can produce a standard report (it will output a string with the report)
 - Save the result of the HTML builder to an actual file (e.g. report_16.html)
end loop

**Comment by xx00a** [comment]
Defer this until after coursework is submitted for ideas and input.

**Comment by xx00a** [comment]
New application structure discussed and implemented. Closed out.
