### ISSUE TITLE
Update README with Screenshots and Progress

### ISSUE THREAD

**Issue by xx00a** [xx00a/Group6#97]
1. Place image (PNG) in /screenshots:

File format: ReportID_**X**.png

**X** = the report number that corresponds with the table on README and your updated application.

2. Update README.md with new counts. See "x requirements of 32 have been implemented". Change this number and update percentage.

3.  Update the README.md report ID table with YES to close off item.

**Comment by xx00a** [comment]
Ferdinand and David to update screenshots based on developed INDEX html page

**Comment by avison9** [comment]
Readme Updated with screen shot and index html page created
